//
//  Product.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.2
//

import Foundation
import UIKit
import AWSDynamoDB

class Product: AWSDynamoDBObjectModel, AWSDynamoDBModeling {
    
    var _userId: String?
    var _productId: String?
    var _companyId: String?
    var _media: [String]?
    var _productDescription: String?
    var _productName: String?
    
    class func dynamoDBTableName() -> String {

        return "mist-mobilehub-605039644-Product"
    }
    
    class func hashKeyAttribute() -> String {

        return "_userId"
    }
    
    class func rangeKeyAttribute() -> String {

        return "_productId"
    }
    
    override class func jsonKeyPathsByPropertyKey() -> [AnyHashable: Any] {
        return [
               "_userId" : "userId",
               "_productId" : "productId",
               "_companyId" : "companyId",
               "_media" : "media",
               "_productDescription" : "productDescription",
               "_productName" : "productName",
        ]
    }
}
