//
//  ProductTable.swift
//  MySampleApp
//
//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.2
//

import Foundation
import UIKit
import AWSDynamoDB
import AWSMobileHubHelper

class ProductTable: NSObject, Table {
    
    var tableName: String
    var partitionKeyName: String
    var partitionKeyType: String
    var sortKeyName: String?
    var sortKeyType: String?
    var model: AWSDynamoDBObjectModel
    var indexes: [Index]
    var orderedAttributeKeys: [String] {
        return produceOrderedAttributeKeys(model)
    }
    var tableDisplayName: String {
        return "Product"
    }
    
    override init() {

        model = Product()
        
        tableName = model.classForCoder.dynamoDBTableName()
        partitionKeyName = model.classForCoder.hashKeyAttribute()
        partitionKeyType = "String"
        indexes = [

            ProductPrimaryIndex(),

            ProductProductId(),
        ]
        if (model.classForCoder.responds(to: #selector(AWSDynamoDBModeling.rangeKeyAttribute))) {
            sortKeyName = model.classForCoder.rangeKeyAttribute!()
            sortKeyType = "String"
        }
        super.init()
    }
    
    /**
     * Converts the attribute name from data object format to table format.
     *
     * - parameter dataObjectAttributeName: data object attribute name
     * - returns: table attribute name
     */

    func tableAttributeName(_ dataObjectAttributeName: String) -> String {
        return Product.jsonKeyPathsByPropertyKey()[dataObjectAttributeName] as! String
    }
    
    func getItemDescription() -> String {
        return "Find Item with userId = \(AWSIdentityManager.default().identityId!) and productId = \("demo-productId-500000")."
    }
    
    func getItemWithCompletionHandler(_ completionHandler: @escaping (_ response: AWSDynamoDBObjectModel?, _ error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        objectMapper.load(Product.self, hashKey: AWSIdentityManager.default().identityId!, rangeKey: "demo-productId-500000", completionHandler: {(response: AWSDynamoDBObjectModel?, error: NSError?) -> Void in
            DispatchQueue.main.async(execute: {
                completionHandler(response, error)
            })
        } as! (AWSDynamoDBObjectModel?, Error?) -> Void)
    }
    
    func scanDescription() -> String {
        return "Show all items in the table."
    }
    
    func scanWithCompletionHandler(_ completionHandler: @escaping (_ response: AWSDynamoDBPaginatedOutput?, _ error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        let scanExpression = AWSDynamoDBScanExpression()
        scanExpression.limit = 5

        objectMapper.scan(Product.self, expression: scanExpression, completionHandler: {(response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void in
            DispatchQueue.main.async(execute: {
                completionHandler(response, error)
            })
        } as! (AWSDynamoDBPaginatedOutput?, Error?) -> Void)
    }
    
    func scanWithFilterDescription() -> String {
        return "Find all items with companyId < \("demo-companyId-500000")."
    }
    
    func scanWithFilterWithCompletionHandler(_ completionHandler: @escaping (_ response: AWSDynamoDBPaginatedOutput?, _ error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        let scanExpression = AWSDynamoDBScanExpression()
        
        scanExpression.filterExpression = "#companyId < :companyId"
        scanExpression.expressionAttributeNames = ["#companyId": "companyId" ,]
        scanExpression.expressionAttributeValues = [":companyId": "demo-companyId-500000" ,]

        objectMapper.scan(Product.self, expression: scanExpression, completionHandler: {(response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void in
            DispatchQueue.main.async(execute: {
                completionHandler(response, error)
            })
        } as! (AWSDynamoDBPaginatedOutput?, Error?) -> Void)
    }
    
    func insertSampleDataWithCompletionHandler(_ completionHandler: @escaping (_ errors: [NSError]?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        var errors: [NSError] = []
        let group: DispatchGroup = DispatchGroup()
        let numberOfObjects = 20
        

        let itemForGet = Product()
        
        itemForGet?._userId = AWSIdentityManager.default().identityId!
        itemForGet?._productId = "demo-productId-500000"
        itemForGet?._companyId = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("companyId")
        itemForGet?._media = NoSQLSampleDataGenerator.randomSampleStringArray()
        itemForGet?._productDescription = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("productDescription")
        itemForGet?._productName = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("productName")
        
        
        group.enter()
        

        objectMapper.save(itemForGet!, completionHandler: {(error: NSError?) -> Void in
            if error != nil {
                DispatchQueue.main.async(execute: {
                    errors.append(error!)
                })
            }
            group.leave()
        } as! (Error?) -> Void)
        
        for _ in 1..<numberOfObjects {

            let item: Product = Product()
            item._userId = AWSIdentityManager.default().identityId!
            item._productId = NoSQLSampleDataGenerator.randomPartitionSampleStringWithAttributeName("productId")
            item._companyId = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("companyId")
            item._media = NoSQLSampleDataGenerator.randomSampleStringArray()
            item._productDescription = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("productDescription")
            item._productName = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("productName")
            
            group.enter()
            
            objectMapper.save(item, completionHandler: {(error: NSError?) -> Void in
                if error != nil {
                    DispatchQueue.main.async(execute: {
                        errors.append(error!)
                    })
                }
                group.leave()
            } as! (Error?) -> Void)
        }
        
        group.notify(queue: DispatchQueue.main, execute: {
            if errors.count > 0 {
                completionHandler(errors)
            }
            else {
                completionHandler(nil)
            }
        })
    }
    
    func removeSampleDataWithCompletionHandler(_ completionHandler: @escaping (_ errors: [NSError]?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        let queryExpression = AWSDynamoDBQueryExpression()
        queryExpression.keyConditionExpression = "#userId = :userId"
        queryExpression.expressionAttributeNames = ["#userId": "userId"]
        queryExpression.expressionAttributeValues = [":userId": AWSIdentityManager.default().identityId!,]

        objectMapper.query(Product.self, expression: queryExpression) { (response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void in
            if let error = error {
                DispatchQueue.main.async(execute: {
                    completionHandler(errors: [error]);
                    })
            } else {
                var errors: [NSError] = []
                let group: DispatchGroup = DispatchGroup()
                for item in response!.items {
                    group.enter()
                    objectMapper.remove(item, completionHandler: {(error: NSError?) -> Void in
                        if error != nil {
                            DispatchQueue.main.async(execute: {
                                errors.append(error!)
                            })
                        }
                        group.leave()
                    })
                }
                group.notify(queue: DispatchQueue.main, execute: {
                    if errors.count > 0 {
                        completionHandler(errors: errors)
                    }
                    else {
                        completionHandler(errors: nil)
                    }
                })
            }
        }
    }
    
    func updateItem(_ item: AWSDynamoDBObjectModel, completionHandler: @escaping (_ error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        

        let itemToUpdate: Product = item as! Product
        
        itemToUpdate._companyId = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("companyId")
        itemToUpdate._media = NoSQLSampleDataGenerator.randomSampleStringArray()
        itemToUpdate._productDescription = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("productDescription")
        itemToUpdate._productName = NoSQLSampleDataGenerator.randomSampleStringWithAttributeName("productName")
        
        objectMapper.save(itemToUpdate, completionHandler: {(error: NSError?) -> Void in
            DispatchQueue.main.async(execute: {
                completionHandler(error)
            })
        } as! (Error?) -> Void)
    }
    
    func removeItem(_ item: AWSDynamoDBObjectModel, completionHandler: @escaping (_ error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        
        objectMapper.remove(item, completionHandler: {(error: NSError?) -> Void in
            DispatchQueue.main.async(execute: {
                completionHandler(error)
            })
        } as! (Error?) -> Void)
    }
}

class ProductPrimaryIndex: NSObject, Index {
    
    var indexName: String? {
        return nil
    }
    
    func supportedOperations() -> [String] {
        return [
            QueryWithPartitionKey,
            QueryWithPartitionKeyAndFilter,
            QueryWithPartitionKeyAndSortKey,
            QueryWithPartitionKeyAndSortKeyAndFilter,
        ]
    }
    
    func queryWithPartitionKeyDescription() -> String {
        return "Find all items with userId = \(AWSIdentityManager.default().identityId!)."
    }
    
    func queryWithPartitionKeyWithCompletionHandler(_ completionHandler: @escaping (_ response: AWSDynamoDBPaginatedOutput?, _ error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        let queryExpression = AWSDynamoDBQueryExpression()
        
        queryExpression.keyConditionExpression = "#userId = :userId"
        queryExpression.expressionAttributeNames = ["#userId": "userId",]
        queryExpression.expressionAttributeValues = [":userId": AWSIdentityManager.default().identityId!,]

        objectMapper.query(Product.self, expression: queryExpression, completionHandler: {(response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void in
            DispatchQueue.main.async(execute: {
                completionHandler(response, error)
            })
        } as! (AWSDynamoDBPaginatedOutput?, Error?) -> Void)
    }
    
    func queryWithPartitionKeyAndFilterDescription() -> String {
        return "Find all items with userId = \(AWSIdentityManager.default().identityId!) and companyId > \("demo-companyId-500000")."
    }
    
    func queryWithPartitionKeyAndFilterWithCompletionHandler(_ completionHandler: @escaping (_ response: AWSDynamoDBPaginatedOutput?, _ error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        let queryExpression = AWSDynamoDBQueryExpression()
        
        queryExpression.keyConditionExpression = "#userId = :userId"
        queryExpression.filterExpression = "#companyId > :companyId"
        queryExpression.expressionAttributeNames = [
            "#userId": "userId",
            "#companyId": "companyId",
        ]
        queryExpression.expressionAttributeValues = [
            ":userId": AWSIdentityManager.default().identityId!,
            ":companyId": "demo-companyId-500000",
        ]
        

        objectMapper.query(Product.self, expression: queryExpression, completionHandler: {(response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void in
            DispatchQueue.main.async(execute: {
                completionHandler(response, error)
            })
        } as! (AWSDynamoDBPaginatedOutput?, Error?) -> Void)
    }
    
    func queryWithPartitionKeyAndSortKeyDescription() -> String {
        return "Find all items with userId = \(AWSIdentityManager.default().identityId!) and productId < \("demo-productId-500000")."
    }
    
    func queryWithPartitionKeyAndSortKeyWithCompletionHandler(_ completionHandler: @escaping (_ response: AWSDynamoDBPaginatedOutput?, _ error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        let queryExpression = AWSDynamoDBQueryExpression()
        
        queryExpression.keyConditionExpression = "#userId = :userId AND #productId < :productId"
        queryExpression.expressionAttributeNames = [
            "#userId": "userId",
            "#productId": "productId",
        ]
        queryExpression.expressionAttributeValues = [
            ":userId": AWSIdentityManager.default().identityId!,
            ":productId": "demo-productId-500000",
        ]
        

        objectMapper.query(Product.self, expression: queryExpression, completionHandler: {(response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void in
            DispatchQueue.main.async(execute: {
                completionHandler(response, error)
            })
        } as! (AWSDynamoDBPaginatedOutput?, Error?) -> Void)
    }
    
    func queryWithPartitionKeyAndSortKeyAndFilterDescription() -> String {
        return "Find all items with userId = \(AWSIdentityManager.default().identityId!), productId < \("demo-productId-500000"), and companyId > \("demo-companyId-500000")."
    }
    
    func queryWithPartitionKeyAndSortKeyAndFilterWithCompletionHandler(_ completionHandler: @escaping (_ response: AWSDynamoDBPaginatedOutput?, _ error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        let queryExpression = AWSDynamoDBQueryExpression()
        
        queryExpression.keyConditionExpression = "#userId = :userId AND #productId < :productId"
        queryExpression.filterExpression = "#companyId > :companyId"
        queryExpression.expressionAttributeNames = [
            "#userId": "userId",
            "#productId": "productId",
            "#companyId": "companyId",
        ]
        queryExpression.expressionAttributeValues = [
            ":userId": AWSIdentityManager.default().identityId!,
            ":productId": "demo-productId-500000",
            ":companyId": "demo-companyId-500000",
        ]
        

        objectMapper.query(Product.self, expression: queryExpression, completionHandler: {(response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void in
            DispatchQueue.main.async(execute: {
                completionHandler(response, error)
            })
        } as! (AWSDynamoDBPaginatedOutput?, Error?) -> Void)
    }
}

class ProductProductId: NSObject, Index {
    
    var indexName: String? {

        return "productId"
    }
    
    func supportedOperations() -> [String] {
        return [
            QueryWithPartitionKey,
            QueryWithPartitionKeyAndFilter,
        ]
    }
    
    func queryWithPartitionKeyDescription() -> String {
        return "Find all items with productId = \("demo-productId-3")."
    }
    
    func queryWithPartitionKeyWithCompletionHandler(_ completionHandler: @escaping (_ response: AWSDynamoDBPaginatedOutput?, _ error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        let queryExpression = AWSDynamoDBQueryExpression()
        

        queryExpression.indexName = "productId"
        queryExpression.keyConditionExpression = "#productId = :productId"
        queryExpression.expressionAttributeNames = ["#productId": "productId",]
        queryExpression.expressionAttributeValues = [":productId": "demo-productId-3",]

        objectMapper.query(Product.self, expression: queryExpression, completionHandler: {(response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void in
            DispatchQueue.main.async(execute: {
                completionHandler(response, error)
            })
        } as! (AWSDynamoDBPaginatedOutput?, Error?) -> Void)
    }
    
    func queryWithPartitionKeyAndFilterDescription() -> String {
        return "Find all items with productId = \("demo-productId-3") and companyId > \("demo-companyId-500000")."
    }
    
    func queryWithPartitionKeyAndFilterWithCompletionHandler(_ completionHandler: @escaping (_ response: AWSDynamoDBPaginatedOutput?, _ error: NSError?) -> Void) {
        let objectMapper = AWSDynamoDBObjectMapper.default()
        let queryExpression = AWSDynamoDBQueryExpression()
        

        queryExpression.indexName = "productId"
        queryExpression.keyConditionExpression = "#productId = :productId"
        queryExpression.filterExpression = "#companyId > :companyId"
        queryExpression.expressionAttributeNames = [
            "#productId": "productId",
            "#companyId": "companyId",
        ]
        queryExpression.expressionAttributeValues = [
            ":productId": "demo-productId-3",
            ":companyId": "demo-companyId-500000",
        ]
        

        objectMapper.query(Product.self, expression: queryExpression, completionHandler: {(response: AWSDynamoDBPaginatedOutput?, error: NSError?) -> Void in
            DispatchQueue.main.async(execute: {
                completionHandler(response, error)
            })
        } as! (AWSDynamoDBPaginatedOutput?, Error?) -> Void)
    }
    
}
